// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901120951_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorias", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("SaldoDisponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoRetenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SaldoDisponible = 0m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 0m,
                            UsuarioId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            SaldoDisponible = 105000m,
                            SaldoRetenido = 45000m,
                            SaldoTotal = 150000m,
                            UsuarioId = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            SaldoDisponible = 200000m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 200000m,
                            UsuarioId = 3,
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            SaldoDisponible = 500m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 500m,
                            UsuarioId = 4,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlIcono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Coleccionables"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Indumentaria"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vehículos"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPuja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubastaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("SubastaId");

                    b.ToTable("Pujas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompradorId = 3,
                            FechaPuja = new DateTime(2026, 9, 1, 11, 49, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            Monto = 20000m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompradorId = 2,
                            FechaPuja = new DateTime(2026, 9, 1, 12, 4, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            Monto = 45000m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompradorId = 3,
                            FechaPuja = new DateTime(2026, 8, 31, 11, 59, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            Monto = 6000m,
                            SubastaId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Subastas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Subasta con 2 pujas.",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 1, 12, 34, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            FechaInicio = new DateTime(2026, 9, 1, 11, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            IncrementoMinimo = 5000m,
                            PrecioBase = 10000m,
                            Titulo = "Activa Estándar",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descripcion = "Alerta visual anti-sniping.",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 1, 12, 10, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            FechaInicio = new DateTime(2026, 9, 1, 11, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            IncrementoMinimo = 1000m,
                            PrecioBase = 5000m,
                            Titulo = "Activa Crítica",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Descripcion = "Inicia mañana.",
                            Estado = "PROGRAMADA",
                            FechaFin = new DateTime(2026, 9, 3, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            FechaInicio = new DateTime(2026, 9, 2, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            IncrementoMinimo = 2000m,
                            PrecioBase = 20000m,
                            Titulo = "Próxima",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            Descripcion = "Esperando liquidación.",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 8, 31, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            FechaInicio = new DateTime(2026, 8, 30, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            IncrementoMinimo = 500m,
                            PrecioBase = 5000m,
                            Titulo = "Vencida con Ganador",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 4,
                            Descripcion = "Nadie pujó.",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 8, 31, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            FechaInicio = new DateTime(2026, 8, 30, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            IncrementoMinimo = 5000m,
                            PrecioBase = 50000m,
                            Titulo = "Vencida Desierta",
                            VendedorId = 1,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.TransaccionLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("SubastaId");

                    b.ToTable("TransaccionesLedger", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 8, 31, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            Monto = 150000m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 2,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 9, 1, 12, 4, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            Monto = 45000m,
                            SubastaId = 1,
                            Tipo = "RETENCION"
                        },
                        new
                        {
                            Id = 3,
                            BilleteraId = 3,
                            Fecha = new DateTime(2026, 8, 31, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            Monto = 200000m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 4,
                            BilleteraId = 4,
                            Fecha = new DateTime(2026, 8, 31, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            Monto = 500m,
                            Tipo = "DEPOSITO"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vendedor@test.com",
                            FechaRegistro = new DateTime(2026, 9, 1, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            Nombre = "Vendedor Test",
                            PasswordHash = "hashed_pw"
                        },
                        new
                        {
                            Id = 2,
                            Email = "comprador1@test.com",
                            FechaRegistro = new DateTime(2026, 9, 1, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            Nombre = "Comprador Líder",
                            PasswordHash = "hashed_pw"
                        },
                        new
                        {
                            Id = 3,
                            Email = "comprador2@test.com",
                            FechaRegistro = new DateTime(2026, 9, 1, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            Nombre = "Comprador Habilitado",
                            PasswordHash = "hashed_pw"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sinfondos@test.com",
                            FechaRegistro = new DateTime(2026, 9, 1, 12, 9, 51, 84, DateTimeKind.Utc).AddTicks(7368),
                            Nombre = "Comprador Sin Fondos",
                            PasswordHash = "hashed_pw"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Billetera", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Puja", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Comprador")
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Domain.Entities.Subasta", b =>
                {
                    b.HasOne("Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Domain.Entities.TransaccionLedger", b =>
                {
                    b.HasOne("Domain.Entities.Billetera", "Billetera")
                        .WithMany("Transacciones")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Subasta", null)
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Billetera");
                });

            modelBuilder.Entity("Domain.Entities.Billetera", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Domain.Entities.Subasta", b =>
                {
                    b.Navigation("Pujas");
                });
#pragma warning restore 612, 618
        }
    }
}
